name: Auto Assign Project

on: [pull_request, issues]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign PR/Issue to "LIFE Engineering's Stop Build Day"
      uses: srggrs/assign-one-project-github-action@1.1.0
      if: github.event.action == 'opened' # not required but speed up the action
      with:
        project: 'https://github.com/Team5830/Infinite-Recharge-Robot/projects/1'
